# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wynnechen/project/EPS_VU13P/lab/lab2_led_status/led_chaser/led_chaser.srcs/sources_1/bd/db/ip/db_util_ds_buf_0_1/db_util_ds_buf_0_1.xci
# IP: The module: 'db_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wynnechen/project/EPS_VU13P/lab/lab2_led_status/led_chaser/led_chaser.gen/sources_1/bd/db/ip/db_util_ds_buf_0_1/db_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'db_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wynnechen/project/EPS_VU13P/lab/lab2_led_status/led_chaser/led_chaser.gen/sources_1/bd/db/ip/db_util_ds_buf_0_1/db_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'db_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/wynnechen/project/EPS_VU13P/lab/lab2_led_status/led_chaser/led_chaser.srcs/sources_1/bd/db/ip/db_util_ds_buf_0_1/db_util_ds_buf_0_1.xci
# IP: The module: 'db_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wynnechen/project/EPS_VU13P/lab/lab2_led_status/led_chaser/led_chaser.gen/sources_1/bd/db/ip/db_util_ds_buf_0_1/db_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'db_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/wynnechen/project/EPS_VU13P/lab/lab2_led_status/led_chaser/led_chaser.gen/sources_1/bd/db/ip/db_util_ds_buf_0_1/db_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'db_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
