set_property SRC_FILE_INFO {cfile:/home/wynnechen/project/EPS_VU13P/lab/lab1_led/LED_lab1/LED_lab1.srcs/constrs_1/new/pin.xdc rfile:../../../LED_lab1.srcs/constrs_1/new/pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports gclk_100m_clk_p]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports led0]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports led1]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports led2]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports led3]
