# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# Block Designs: bd/db/db.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==db || ORIG_REF_NAME==db} -quiet] -quiet

# IP: bd/db/ip/db_util_ds_buf_0_0/db_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==db_util_ds_buf_0_0 || ORIG_REF_NAME==db_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/db/ip/db_util_ds_buf_0_1/db_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==db_util_ds_buf_0_1 || ORIG_REF_NAME==db_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/db/ip/db_led_chaser_0_0/db_led_chaser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==db_led_chaser_0_0 || ORIG_REF_NAME==db_led_chaser_0_0} -quiet] -quiet

# IP: bd/db/ip/db_vio_0_0/db_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==db_vio_0_0 || ORIG_REF_NAME==db_vio_0_0} -quiet] -quiet

# IP: bd/db/ip/db_ila_0_0/db_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==db_ila_0_0 || ORIG_REF_NAME==db_ila_0_0} -quiet] -quiet

# XDC: /home/wynnechen/project/haps-sx/lab/lab2/led_chaser/led_chaser.gen/sources_1/bd/db/db_ooc.xdc
